name: mlkit_scan_plugin_example
description: Demonstrates how to use the mlkit_scan_plugin plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mlkit_scan_plugin:
    path: ../

  permission_handler: ^9.2.0

flutter:
  uses-material-design: true

